### ISSUE TITLE
Github SourceContext in Deployment Settings

### ISSUE THREAD

**Issue by SpainTrain** [pulumi/pulumi-pulumiservice#155]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, DeploymentSettings appears to only support the `git` SourceContext.  Being able to use `Github` would be preferred for those who use the Github App for Pulumi Deployments.

As an interim solution (but may admittedly be gross), having a way to indicate "leave manually setup SourceContext alone" would at least provide a way to manage the rest of DeploymentSettings with this provider and set SourceContext manually until fully implemented.

As a bit more context - the problem I am trying to solve is automating setup of GCP OIDC for Pulumi Deployments.  I would like to, in a stack, be able to create the GCP resources for workload identity pool etc., then place the relevant outputs of those resources as inputs into `OperationContext -> oidc`.

### Affected area/feature

https://github.com/pulumi/pulumi-pulumiservice/blob/main/provider/pkg/provider/deployment_settings.go

**Comment by SpainTrain** [comment]
CC @MitchellGerdisch

**Comment by EvanBoyle** [comment]
@SpainTrain you can indeed use the provider to configure deployment settings via the github app. The `sourceContext.gitHub` field is deprecated and not relevant, you should instead use the top level `github` parameter as shown here: 

```ts
    const productionSettings = new pulumiservice.DeploymentSettings("productionSettings", {
        github: {
            deployCommits: true,
            previewPullRequests: true,
            repository: "ghOrgName/repoName",
        },
        organization: "orgName",
        project: "projectName",
        sourceContext: {
            git: {
                branch: "refs/heads/main",
            },
        },
        stack: "production",
    });
```

I'm to go ahead and close this one out. Feel free to reopen if you're still having problems.
