### ISSUE TITLE
Create a new resource `stack`

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-pulumiservice#171]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When running `pulumi new ...` or `pulumi stack init`, it would be helpful if this provider could create new empty stacks and manage the stack through this provider.

**Comment by IaroslavTitov** [comment]
Hello there!
Would you please explain the use case for a resource like that? Like, why would like to create empty stacks?

Normally, anytime you want to create new resources, a stack is created as part of `pulumi up`, through pulumi CLI or deployments, or whichever way.
This provider is for Pulumi Cloud resources, while Stacks are a concept whether you're using Pulumi Cloud or not.

**Comment by IaroslavTitov** [comment]
Chatted on slack, the intent is to enforce a naming pattern on stacks, by essentially "reserving" a stack name, then adding TeamStackPermissions to a specific team to work on it.
