### ISSUE TITLE
Add TeamEnvironmentPermission resource

### ISSUE THREAD

**Issue by theplatformer** [pulumi/pulumi-pulumiservice#179]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

With the introduction of Pulumi ESC it would be very useful for this provider to be able to create/delete an Environment, as well as grant Environment permissions to Teams. We use a centralised GitHub repo and this provider to provide a self-service way for teams to manage things like Pulumi Cloud Teams and Stack Permissions for those Teams. We would like to do the same for Environments.

There is a wider issue (https://github.com/pulumi/esc/issues/63) describing the ability to manage the desired state of an Environment from this provider. This request however is simply to manage the existence of the Environment and Team permissions for it, not the state within it.

### Examples

```typescript
const env = new pulumiservice.Environment("team-owned-environment", {
    organization: "acme-corp",
    name: "team-owned-environment",
});
```

```typescript
new pulumiservice.TeamEnvironmentPermission(
    "team-a-team-owned-environment,
    {
        organization: "acme-corp",
        team: "team-a",
        environment: "team-owned-environment",
        permission: pulumiservice.TeamEnvironmentPermissionScope["Write"],
    },
    { dependsOn: env },
);
```

### Affected area/feature

- Pulumi ESC
- Pulumi Cloud Service

**Comment by komalali** [comment]
Renaming this issue to specifically be about TeamEnvironmentPermission - tracking the Environment resource in https://github.com/pulumi/pulumi-pulumiservice/issues/225

**Comment by IaroslavTitov** [comment]
Resolved in https://github.com/pulumi/pulumi-pulumiservice/pull/279
Closing issue

Environment resource will be added in https://github.com/pulumi/pulumi-pulumiservice/pull/271, as part of another [issue](https://github.com/pulumi/pulumi-service/issues/19533)
