### ISSUE TITLE
Cannot create org webhook for ms teams

### ISSUE THREAD

**Issue by sebastianfeduniak** [pulumi/pulumi-pulumiservice#188]
### What happened?

I tried to create org webhook for MS Teams in accordance to the official example: https://www.pulumi.com/blog/ms-teams-integration/#pulumi-service-provider

I am using pulumi organization access token.

In accordance to the doc: https://www.pulumi.com/docs/pulumi-cloud/access-management/access-tokens/
it should be possible, but if fails with:

```
failed: failed to create webhook: 403 API error: You do not have permission to perform this operation.
```

### Example

1. Create pulumi organization access token
2. Use it to create the following webhook:

```
new Webhook('webhook-for-ms-teams', {
    active: true,
    displayName: 'webhook-for-ms-teams',
    organizationName: '***',
    payloadUrl: config.requireSecret('orgWebhook'),
    format: WebhookFormat.MicrosoftTeams,
    filters: [
      WebhookFilters.PreviewFailed,
      WebhookFilters.PreviewSucceeded,
      WebhookFilters.UpdateFailed,
      WebhookFilters.UpdateSucceeded,
    ],
  });
```

### Output of `pulumi about`

CLI
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME            VERSION
aws             6.7.0
awsx            2.0.3
confluentcloud  1.27.0
datadog         4.12.0
docker          4.4.4
docker          3.6.1
docker          3.6.1
github          4.10.0
nodejs          unknown
postgresql      3.6.0
pulumiservice   0.14.0
random          4.3.1

Host
OS       darwin
Version  12.7
Arch     x86_64

### Additional context

I1106 13:02:33.010245    8187 log.go:81] GetProvider(urn:pulumi:build::***::pulumi:providers:pulumiservice::default_0_14_0::cb9b21da-2b14-4d3d-b623-8780df08c823)
I1106 13:02:33.010213    8187 log.go:81] Marked old state snapshot as done: urn:pulumi:build::***::pulumi:pulumi:StackReference::***/***/dev
I1106 13:02:33.010294    8187 log.go:81] Appended new state snapshot to be written: urn:pulumi:build::***::pulumi:pulumi:StackReference::***/***/dev
I1106 13:02:33.010265    8187 log.go:81] Provider[pulumiservice, 0xc001736730].Create(urn:pulumi:build::***::pulumiservice:index:Webhook::pulumi-org-webhook-for-ms-teams) executing (#props=6)
I1106 13:02:33.010358    8187 log.go:81] Marshaling property for RPC[Provider[pulumiservice, 0xc001736730].Create(urn:pulumi:build::***::pulumiservice:index:Webhook::pulumi-org-webhook-for-ms-teams).inputs]: active={true}
I1106 13:02:33.010381    8187 log.go:81] Marshaling property for RPC[Provider[pulumiservice, 0xc001736730].Create(urn:pulumi:build::***::pulumiservice:index:Webhook::pulumi-org-webhook-for-ms-teams).inputs]: displayName={pulumi-org-webhook-for-ms-teams}
I1106 13:02:33.010401    8187 log.go:81] Marshaling property for RPC[Provider[pulumiservice, 0xc001736730].Create(urn:pulumi:build::***::pulumiservice:index:Webhook::pulumi-org-webhook-for-ms-teams).inputs]: filters={[{preview_failed} {preview_succeeded} {update_failed} {update_succeeded}]}
I1106 13:02:33.010423    8187 log.go:81] Marshaling property for RPC[Provider[pulumiservice, 0xc001736730].Create(urn:pulumi:build::***::pulumiservice:index:Webhook::pulumi-org-webhook-for-ms-teams).inputs]: format={ms_teams}
I1106 13:02:33.010435    8187 log.go:81] Marshaling property for RPC[Provider[pulumiservice, 0xc001736730].Create(urn:pulumi:build::***::pulumiservice:index:Webhook::pulumi-org-webhook-for-ms-teams).inputs]: organizationName={***}
I1106 13:02:33.010452    8187 log.go:81] Marshaling property for RPC[Provider[pulumiservice, 0xc001736730].Create(urn:pulumi:build::***::pulumiservice:index:Webhook::pulumi-org-webhook-for-ms-teams).inputs]: payloadUrl={[secret]}
I1106 13:02:33.787246    8187 log.go:81] Provider[pulumiservice, 0xc001736730].Create(urn:pulumi:build::***::pulumiservice:index:Webhook::pulumi-org-webhook-for-ms-teams) failed: failed to create webhook: 403 API error: You do not have permission to perform this operation.
I1106 13:02:33.787274    8187 log.go:81] eventSink::Error(<{%reset%}>failed to create webhook: 403 API error: You do not have permission to perform this operation.<{%reset%}>)
 +  pulumiservice:index:Webhook pulumi-org-webhook-for-ms-teams creating (2s) error: failed to create webhook: 403 API error: You do not have permission to perform this operation.
I1106 13:02:33.787416    8187 log.go:81] SnapshotManager: createSnapshotMutation.End(..., false)
 +  pulumiservice:index:Webhook pulumi-org-webhook-for-ms-teams **creating failed** error: failed to create webhook: 403 API error: You do not have permission to perform this operation.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by komalali** [comment]
Thanks for the issue @sebastianfeduniak. I believe this is a documentation oversight, organization webhooks require admin privileges, and therefore would require an admin token. We'll be sure to get the docs updated
