### ISSUE TITLE
Add ESC Environment Resource to the Pulumi Cloud Provider

### ISSUE THREAD

**Issue by desteves** [pulumi/pulumi-pulumiservice#225]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I have a Pulumi program with AWS Resources; in this same program, I'd like to create a new ESC Environment. I can do so using axios and [this REST API](https://www.pulumi.com/docs/pulumi-cloud/cloud-rest-api/#create-environment), but it's messy.

### Affected area/feature

Pulumi Service

**Comment by lukehoban** [comment]
Related to https://github.com/pulumi/pulumi-pulumiservice/issues/179 and https://github.com/pulumi/pulumi-pulumiservice/issues/63.
