### ISSUE TITLE
Deployment resource does not support Deployment Runner Pool selection.

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-pulumiservice#227]
### What happened?

The PulumiService provider Deployment resource does not support setting the Deployment Runner Pool.

### Example

https://www.pulumi.com/registry/packages/pulumiservice/api-docs/deploymentsettings/

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by komalali** [comment]
Fixed by https://github.com/pulumi/pulumi-pulumiservice/pull/228
