### ISSUE TITLE
TtlSchedule and DriftSchedule - pulumi refresh loses schedule ID so update adds schedule

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-pulumiservice#257]
### What happened?

I have a stack with a TtlSchedule resource and DriftSchedule resource.
If I run `pulumi refresh -y` the schedules' ids are removed from state.
So, if change the resource (say modify the time or cron) a subsequent `pulumi up` creates additional schedules.

### Example

- Use your favorite pulumi (python) program/stack with deployments configured and add the code below.
- `pulumi up -y`
- See the two schedules that were created.
- `pulumi refresh -y`
   - Note that schedule Ids were removed from state
- Modify the two schedule resources by modifying the time or cron properties
- `pulumi up -y`
- In Pulumi Cloud UI see that there are now two of each type of schedule instead of just modifying the original schedules.

```
org = pulumi.get_organization()
project = pulumi.get_project()
stack = pulumi.get_stack()

ttlSchedule = ps.TtlSchedule("ttlsched", 
                             organization=org,
                             project=project,
                             stack=stack,
                             timestamp="2024-07-01T00:00:00Z",
                             delete_after_destroy=False)

driftSchedule = ps.DriftSchedule("driftsched", 
                             organization=org,
                             project=project,
                             stack=stack,
                             schedule_cron="0 * * * *") 
```

### Output of `pulumi about`

CLI          
Version      3.113.3
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  aws            6.32.0
resource  pulumiservice  0.20.0
language  python         unknown
resource  stackmgmt      3.1.0

Host     
OS       darwin
Version  13.6.6
Arch     x86_64

This project is written in python: version='3.10.11'

Backend        
Name           pulumi.com

Dependencies:
NAME              VERSION
pequod-stackmgmt  3.1.0
pip               23.0.1
pulumi_aws        6.32.0
setuptools        65.5.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by MitchellGerdisch** [comment]
This also makes it impossible to destroy the stack without state surgery due to this error:
`    error: failed to delete schedule with scheduleId  : failed to parse response body, status code 404: invalid character 'p' after top-level value`

**Comment by IaroslavTitov** [comment]
This is fixed in [pull request](https://github.com/pulumi/pulumi-pulumiservice/pull/260), resolving the issue. We will do a new release of the provider this week, so that the change will be live. Resolving the issue.
