### ISSUE TITLE
pulumi-pulumiservice v0.18.0 breaks backward compatibility with deployment settings 

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi-pulumiservice#262]
This change [`v0.17.0...v0.18.0`#diff-e8f12ff3d2](https://github.com/pulumi/pulumi-pulumiservice/compare/v0.17.0...v0.18.0#diff-e8f12ff3d252132d6793808534f6afbc3ffa6a79825538ef7fe404fe8064e7c3R218) broke older versions of deployment settings that are using executor images that don't require credentials. We'll need to update pulumi/pulumi to conditionally unmarshal the deployment settings object like we do in pulumi-service, and then pull in those changes to this provider to fix the issue.

**Comment by IaroslavTitov** [comment]
Created [PR](https://github.com/pulumi/pulumi-pulumiservice/pull/263) for pulling in the pu/pu change + serialization fix in provider. Once this is in, issue will be done.

**Comment by komalali** [comment]
Fixed by https://github.com/pulumi/pulumi-pulumiservice/pull/263
