### ISSUE TITLE
Provide Input<string> for YAML field in provider

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi-pulumiservice#327]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Rather than have to write a bunch of additional boilerplate to convert to a promise and then an asset it would be good to just pass an input string.

I had to do the following in ts to achieve this:

```ts
 yaml: new pulumi.asset.StringAsset(
                    environment({
...
const environment = (args: {
    subName: string
    clientId: pulumi.Input<string>
    tenantId: pulumi.Input<string>
    subscriptionId: pulumi.Input<string>
}) =>
    PromisifyOutput<string>(pulumi.interpolate`
values:
  azure:
    login:
...
export function PromisifyOutput<T>(output: pulumi.Output<T>): Promise<T> {
    return new Promise((resolve) => output.apply(resolve))
}
```

which would become 

```ts
 yaml: pulumi.interpolate`
values:
  azure:
    login:
...
```

### Affected area/feature

esc provider

**Comment by IaroslavTitov** [comment]
Good morning
Please take a look at our TS example of creating Environment resource [here](https://github.com/pulumi/pulumi-pulumiservice/blob/main/examples/ts-environments/index.ts#L9-L15)
It should be pretty straightforward to turn a String into a StringAsset using `new pulumi.asset.StringAsset(stringInput)`

Does this solve your issue? I might have misunderstood

**Comment by liamawhite** [comment]
StringAsset doesn't take a `Input<string>` only a `Promise<string>`, hence the boilerplate. If the StringAsset took a. `Input<string>` that would also solve the problem.

**Comment by IaroslavTitov** [comment]
Oh, sorry I did not see the `interpolate` method at first. So the trouble is converting `Output<string>` into a `StringAsset`

I just tested the code below:
```
let yaml = pulumi.interpolate
    `values:
      myKey1: "myValue1"
      myNestedKey:
        myKey2: "myValue2"
        myNumber: 1`
        
var environment = new service.Environment("testing-environment", {
    organization: "service-provider-test-org",
    name: "testing-environment-ts",
    yaml: yaml.apply((y) => new pulumi.asset.StringAsset(y))
  })
```

You can convert `Output<string>`, by using the `apply` method, which extracts the underlying string, that can then be wrapped into `StringAsset` - `yaml.apply((y) => new pulumi.asset.StringAsset(y))`. I think you're already doing it very similarly in your code.
I understand it's not as straightforward as `yaml: yaml` would have been. I think we went with Asset instead of string here to make loading environment yamls from files easier.

Does that help?

**Comment by liamawhite** [comment]
Yes that's easier than my approach. But I still don't fully understand why `StringAsset` doesn't accept an `Output<string>` like almost every other resource! 😅

**Comment by IaroslavTitov** [comment]
For `why StringAsset doesn't accept an Output<string>`, I'm not sure myself, could be worth opening an issue in pulumi/pulumi, maybe the core team can make it happen.

`StringAsset` is not *technically* a resource, just a [Pulumi helper type, like Output or Archive,](https://www.pulumi.com/docs/iac/concepts/assets-archives/) so I think it's ok 😅 

Either way, thanks for filing the ticket, please continue report any bugs or filing enchancements you'd like to see!
