### ISSUE TITLE
Publish Java Package to Maven Central

### ISSUE THREAD

**Issue by JaseKirby** [pulumi/pulumi-pulumiservice#329]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Publish java package to [maven central](https://central.sonatype.com/) instead of hosting in GitHub packages which requires authentication for installation.

**Comment by IaroslavTitov** [comment]
Work on this started in https://github.com/pulumi/pulumi-pulumiservice/pull/446, migrating all of PSP release logic to catch up with other providers

**Comment by IaroslavTitov** [comment]
This should come as part of https://github.com/pulumi/pulumi-pulumiservice/issues/338, but not resolving until I can confirm.

**Comment by blampe** [comment]
The upcoming release of the provider for #455 will include Java publishing.

**Comment by blampe** [comment]
https://central.sonatype.com/artifact/com.pulumi/pulumiservice/0.27.2
