### ISSUE TITLE
Add to ci-mgmt 

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi-pulumiservice#338]
You might want to consider putting this provider under ci-mgmt so it can maintain these workflows for you.

_Originally posted by @blampe in https://github.com/pulumi/pulumi-pulumiservice/pull/337#pullrequestreview-2140122389_

**Comment by IaroslavTitov** [comment]
Work on this started in https://github.com/pulumi/pulumi-pulumiservice/pull/446, migrating all of PSP release logic to catch up with other providers
