### ISSUE TITLE
AccessToken refresh clears value

### ISSUE THREAD

**Issue by muhlba91** [pulumi/pulumi-pulumiservice#359]
### What happened?

I am creating access tokens when bootstrapping repositories. These get then stored in the GitHub repository and/or a Vault instance.
This was working fine until the refactoring of the access token read method was done as since then a refresh clears the token value, which makes sense because the Pulumi API doesn't return the token but https://github.com/pulumi/pulumi-pulumiservice/blob/main/provider/pkg/provider/access_token.go#L128 and ultimately https://github.com/pulumi/pulumi-pulumiservice/blob/main/provider/pkg/provider/access_token.go#L30 assumes a token to be present.

This behaviour breaks my automation because on the next run, all stored tokens are cleared in GitHub/Vault and, in the end, all pipelines using these tokens are failing.

The same seems to happen with the description field.

### Example

1. Create a `AccessToken` resource, and print the `value` (it seems like `description` is also cleared).
2. Call `pulumi up` and check the token.
3. Call `pulumi refresh`.
4. Call `pulumi up` again and the token is cleared.

### Output of `pulumi about`

```
CLI
Version      3.125.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  aws            6.45.0
resource  gcp            7.32.0
resource  github         6.2.3
language  nodejs         unknown
resource  pulumiservice  0.22.2
resource  random         4.16.3
resource  time           0.0.17
resource  vault          6.2.0

Host
OS       darwin
Version  15.0
Arch     arm64

This project is written in nodejs: executable='/Users/daniel/.nvm/versions/node/v20.15.1/bin/node' version='v20.15.1'

<truncated>

Found no pending operations associated with prod

Backend
Name           pulumi.com
URL            https://app.pulumi.com/muhlba91
User           muhlba91
Organizations  muhlba91
Token type     personal

Dependencies:
NAME                      VERSION
@pulumi/aws               6.45.0
@pulumi/gcp               7.32.0
@pulumi/github            6.2.3
@pulumi/pulumi            3.125.0
@pulumi/pulumiservice     0.22.2
@pulumi/random            4.16.3
@pulumi/vault             6.2.0
@pulumiverse/time         0.0.17
@types/nunjucks           3.2.6
nunjucks                  3.2.4
yaml                      2.4.5
eslint                    9.7.0
eslint-config-prettier    9.1.0
eslint-plugin-functional  6.6.3
eslint-plugin-import      2.29.1
npm-run-all2              6.2.2
prettier                  3.3.3
ts-node                   10.9.2
typedoc                   0.26.4
typescript                5.5.3
typescript-eslint         7.16.1

Pulumi locates its logs in /var/folders/v5/n7c212tn57v8mx8xtkm00wqc0000gn/T/ by default
```

### Additional context

FYI: I implemented the previous support for refreshing the token as per https://github.com/pulumi/pulumi-pulumiservice/pull/177.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by IaroslavTitov** [comment]
Good afternoon
Thank you for documenting the issue - I looked into it and realized that I indeed missed logic that accounts for value and description. I will make a fix and release it as soon as possible.
Sorry about that!

**Comment by IaroslavTitov** [comment]
Release for 0.22.3 is out, please update to this new version - that should fix the issue.

**Comment by muhlba91** [comment]
awesome, thank you for the fix! 👍
