### ISSUE TITLE
Unable to delete Deployment Agent Pool once used with a Stack Deplyment Settings

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-pulumiservice#378]
### What happened?

I'm unable to delete a Deployment Agent Pool, is this agent pool was previously associated to a stack deployment settings. The Pulumi Service (this provider and the API) return the following error message: `Stacks have been configured to use deployment pool: "agent-pool". Please change the stack deployment configuration before deleting this pool.` ❌

However, when looking at the Pulumi Cloud Console UI, I see the deployment settings are gone ✔, and the UI shows the `Pulumi hosted pool` is selected ✔.

With the program below here are the steps to reproduce.

1. Init a new stack
2. Select the new stack
3. Deploy the code shown below ✔
4. Comment the resource `pulumiservice.DeploymentSettings()`
5. Deploy the updated code ✔
6. Comment the last resource `pulumiservice.AgentPool()`
7. Deploy the updated code (or destroy the stack) ❌

At step 7, the update fails and an error is returned
```
error: failed to delete agent pool "f4259249-76dd-4e54-9979-f64ff0ba50fb": 400 API error: Bad Request: Stacks have been configured to use deployment pool: "agent-pool". Please change the stack deployment configuration before deleting this pool.
```

To recover from this situation, a user must go through the following steps
1. Connect to the Pulumi Cloud Console
2. Go to the Deployment settings in the relevant stack (the `Pulumi Hosted Pool` is already selected)
3. Enter new settings for `Source control settings`
4. Save the new settings
5. Update (or destroy) the stack so the Deployment Pool can be deleted

### Example

```python
"""A Python Pulumi program"""

import pulumi
import pulumi_pulumiservice as pulumiservice

agent_pool = pulumiservice.AgentPool(
    name="agent-pool",
    resource_name="agent-pool",
    organization_name=pulumi.get_organization(),
)

deployment_settings = pulumiservice.DeploymentSettings(
    resource_name = "deployment-settings",
    organization = pulumi.get_organization(),
    project = pulumi.get_project(),
    stack = pulumi.get_stack(),
    agent_pool_id=agent_pool.agent_pool_id,
    source_context = pulumiservice.DeploymentSettingsSourceContextArgs(
        git = pulumiservice.DeploymentSettingsGitSourceArgs(
            branch = "main",
            repo_url = "aureq/aws-py-eks-helm",
            git_auth = pulumiservice.DeploymentSettingsGitSourceGitAuthArgs(
                basic_auth = pulumiservice.DeploymentSettingsGitAuthBasicAuthArgs(
                    username = "aureq",
                    password = "<redacted>"
                )
            )
        )
    ),
    operation_context = pulumiservice.DeploymentSettingsOperationContextArgs(
        environment_variables = {
            "SECRET_ENV_VAR": pulumi.Output.secret('This should NOT be visible')
        }
    )
)
```

### Output of `pulumi about`

```
CLI          
Version      3.129.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  pulumiservice  0.23.1
language  python         unknown

Host     
OS       debian
Version  12.6
Arch     x86_64

This project is written in python: executable='/home/aureq/work/customers/zendesk/5662/venv/bin/python' version='3.11.9'

Current Stack: menfin/zendesk/5662

TYPE                            URN
pulumi:pulumi:Stack             urn:pulumi:5662::zendesk::pulumi:pulumi:Stack::zendesk-5662
pulumi:providers:pulumiservice  urn:pulumi:5662::zendesk::pulumi:providers:pulumiservice::default_0_23_1
pulumiservice:index:AgentPool   urn:pulumi:5662::zendesk::pulumiservice:index:AgentPool::agent-pool


Found no pending operations associated with 5662

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo
Token type     personal

Dependencies:
NAME                  VERSION
pip                   24.2
pulumi-pulumiservice  0.23.1
setuptools            72.2.0
wheel                 0.44.0

Pulumi locates its logs in /tmp by default
```

### Additional context

Screenshot taken after repro step 3.
![Image](https://github.com/user-attachments/assets/6771b0f4-cd16-48dc-bcd7-d671370ca07a)

Screenshot taken after repro step 5
![Image](https://github.com/user-attachments/assets/daf27934-3a26-40d7-846b-dfa8d105c114)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by komalali** [comment]
I'm not sure why this is a bug? There is a dependency between the deployment settings and the agent pool. If the deployment settings have not been deleted you should not be able to delete the agent pool.

**Comment by komalali** [comment]
Ah I see it seems like we don't allow you to delete it even if you delete the deployment settings. @glena I wonder if this is related to the soft delete of deployment settings?
