### ISSUE TITLE
[doc] Add preview note to README and registry

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-pulumiservice#380]
### What happened?

Let's ensure that the README clearly indicates that the Pulumi Service provider is in public preview. Also let's make sure this shows up in the Pulumi registry like it's currently done for the AWS native provider.

![Image](https://github.com/user-attachments/assets/e280bad1-123c-4c2c-8c24-5a31d01a1fe9)

### Example

n/a

### Output of `pulumi about`

n/a

### Additional context

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by IaroslavTitov** [comment]
Working on [PSPV1](https://github.com/pulumi/pulumi-pulumiservice/issues/413) to not need the preview info, but can implement for now.

Looking into it noticed we do need to update registry landing page for PSP though, the name is confusing - https://www.pulumi.com/registry/packages/pulumiservice/
