### ISSUE TITLE
Support for `PolicyPack` and `PolicyGroup` resources

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-pulumiservice#428]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be great for this provider to support both policy packs and policy groups resource management.

([context](https://pulumi.slack.com/archives/C07T20FQVNJ/p1729725343880419))

### Affected area/feature

* policy as code / crossguard
* provider

**Comment by rshade** [comment]
this looks to be a duplicate of #186
