### ISSUE TITLE
Support team-stack permissions

### ISSUE THREAD

**Issue by mchaynes** [pulumi/pulumi-pulumiservice#51]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

@MitchellGerdisch commented on the initial request to create the pulumi service provider to add team-stack permissions:
> The provider should support team-stack permissions assignment management

https://github.com/pulumi/service-requests/issues/18#issuecomment-1017599144

**Comment by sinePaul** [comment]
Hello, 
I will be interested to implement this feature :)
