### ISSUE TITLE
Create access token + github action example

### ISSUE THREAD

**Issue by mchaynes** [pulumi/pulumi-pulumiservice#60]
We should provide an example that makes the [Pulumi CLI Action](https://github.com/marketplace/actions/pulumi-cli-action)  from the marketplace even easier by automatically creating and injecting a pulumi access token into a Github action [environment secret](https://www.pulumi.com/registry/packages/github/api-docs/actionsenvironmentsecret/).

This would reduce the friction of setting up a new project with pulumi configured by a lot, since there will be less context switching between the dev's editor/terminal and the pulumi service's web UI.

**Comment by IaroslavTitov** [comment]
Today, we have OIDC auth as an alternative for easy use in GHA. Confirmed with @komalali, we won't implement this.
