### ISSUE TITLE
Add additional option to get credentials

### ISSUE THREAD

**Issue by Eric-Swiftly** [pulumi/pulumi-pulumiservice#63]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently there are 3 ways to get credentials to the provider.
set via environment variable
A config file setting
passed as a value while creating a provider.

The first requires an action by users when they checkout the repo.  The second two would require checking in a token to a source repository which is a big no-no.

The users token is already stored in the credentials.json (located in .pulumi/credentials.json in Unix) It would be nice if a 4th option was added to read the credentials from the credentials.json.

**Comment by mchaynes** [comment]
This seems like a reasonable ask to me. The main blocker I see is defining the contract between the pulumi CLI and the pulumi service provider so we can guarantee that this will work as the pulumi CLI is updated. I've filed https://github.com/pulumi/pulumi/issues/9679 to discuss this.
