### ISSUE TITLE
Migrate Java publishing SDK to use new java publishing sdk

### ISSUE THREAD

**Issue by mchaynes** [pulumi/pulumi-pulumiservice#82]
To simplify our java SDK publishing, we should migrate this repo from our handrolled java SDK publishing to instead use the same method that pulumi-kubernetes migrated to in https://github.com/pulumi/pulumi-kubernetes/pull/2096

**Comment by IaroslavTitov** [comment]
Resolving this in favor of https://github.com/pulumi/pulumi-pulumiservice/issues/338, which is an even newer release solution
