### ISSUE TITLE
Migrate to pulumi-go-provider

### ISSUE THREAD

**Issue by mchaynes** [pulumi/pulumi-pulumiservice#84]
The https://github.com/pulumi/pulumi-go-provider framework has the potential to massively simplify development on this provider, which will speed up the development of future resource types. We should do some investigation into whether it will work for us or not.

Migrating to this framework will close these issues as well:
* https://github.com/pulumi/pulumi-pulumiservice/issues/57
* https://github.com/pulumi/pulumi-pulumiservice/issues/56
* https://github.com/pulumi/pulumi-pulumiservice/issues/55

**Comment by IaroslavTitov** [comment]
Resolving in favor of https://github.com/pulumi/pulumi-pulumiservice/issues/288, duplicate
