### ISSUE TITLE
Problems updating a stack tag's value

### ISSUE THREAD

**Issue by christophermaier** [pulumi/pulumi-pulumiservice#86]
### What happened?

This is a follow-up to #75; the background and reproduction steps on that issue are still applicable here.

Now, I'm able to change a tag value in the SaaS, but still get empty diffs on subsequent `pulumi up` calls.

Attempting to delete the tag now results in the following error message:
```
error: failed to make request: failed to parse response body, status code 404: invalid character 'p' after top-level value
```

### Steps to reproduce

See #75.

### Expected Behavior

A stack tag should be able to be renamed.

### Actual Behavior

See above.

### Output of `pulumi about`

```
CLI          
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME           VERSION
pulumiservice  unknown
yaml           unknown

Host     
OS       debian
Version  11.4
Arch     x86_64
```
Though the version of the `pulumiservice` plugin isn't displayed in `pulumi about`, I'm using v0.1.6, based on the contents of `~/.pulumi/plugins`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by christophermaier** [comment]
Thanks, @mchaynes! 🙏

**Comment by mchaynes** [comment]
No problem at all 😄 @christophermaier
