### ISSUE TITLE
Upload releases to get.pulumi.com

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-pulumiservice#92]
GoReleaser currently isn't uploading the binaries to the release S3 bucket, and some customers rely on that. We should publish binaries to it.

**Comment by mchaynes** [comment]
PR to fix: https://github.com/pulumi/pulumi-pulumiservice/pull/93

We will need to run a release to test that this works

**Comment by mchaynes** [comment]
Artifacts are now uploaded to get.pulumi.com.
